name: iOS starter workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
  
      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
  
      - name: Configure Bundler path
        run: bundle config set path 'vendor/bundle'
  
      - name: Install dependencies
        run: |
          cd Example/api
          gem install bundler
          bundle install
  
      - name: Install Fastlane
        run: |
          cd Example/api
          bundle exec fastlane tests

      
      
